"""Initial migration with licensing updates

Revision ID: 007efff5cc99
Revises: 
Create Date: 2026-03-15 10:12:46.943779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007efff5cc99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_completions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_completions', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
